{
  "name": "jinsmeme_electron",
  "version": "0.4.0",
  "description": "jinsmeme integration sample for electron",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "JINS Corp.",
  "license": "JINS MEME terms of use",
  "devDependencies": {
    "electron": "^2.0.8"
  },
  "dependencies": {
    "noble": "^1.9.1",
    "node-rest-client": "^3.1.0"
  }
}
